### ISSUE TITLE
可以借鉴设计效果么

### ISSUE THREAD

**Issue by nanhupatar** [oxxostudio/oxxostudio.github.io#1]
觉得设计的很棒，我想借鉴设计效果，然后迁移到hexo主体中进行开源。由于仓库没有开源证书，在这里询问一下

**Comment by oxxostudio** [comment]
哈囉你好，謝謝您的支持，關於設計風格目前還沒有開源的想法，畢竟視覺設計開源比較不像程式碼開源，如果大家都用同樣的設計風格，就少了些原汁原味了 ( 這也是為什麼我要自己從無到有做一個部落格，不套用現成版型的原因 )
不過還是很感謝您的支持和鼓勵呦！^_^

**Comment by nanhupatar** [comment]
感谢回复，请问博客是用了什么驱动么
